# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86558ed18e075dfb3bd7d9757b85c4764dd33be462edd8bc6a0fde0c56162303d6c3b03c63ed303dd45d8f8a2f4f7094bdabd12fb83925dbdf9b75d1d4eb0f01

test:
  secret_key_base: 73a0bb5be85a26e64d24662a341f38b8923ceef91ab033b84256166440cf8a5307b7833095f89eb03f2aee210e6e065714593237ea648bd6886d601164e4a1b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
